name = "StaticLLVM"
uuid = "2455efbc-c9b1-401c-8032-01f10eed9ad1"
authors = ["kylin <kylincaster@foxmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
ArgParse = "1.2.0"
InteractiveUtils = "1.11.0"
ProgressMeter = "1.10.4"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
